# Display Dynamic Tab

#### Imports

In [1]:
from autotab.TabPrediction import load_model_and_weights
from autotab.TabPrediction import load_x_new
from autotab.TabPrediction import make_full_tab
import autotab.TabPrediction as tp

2021-11-30 18:31:33.935873: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2021-11-30 18:31:33.936161: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.

## Build model and load weights

In [2]:
model = load_model_and_weights()

Using Google cloud buckets
BUCKET_NAME wagon-data-737-sadriwala
DATA_BUCKET_FOLDER data/spec_repr
gs://wagon-data-737-sadriwala/data/spec_repr/
gs://wagon-data-737-sadriwala/saved/
getting ids from gs://wagon-data-737-sadriwala/data/spec_repr/id.csv

2021-11-30 18:32:03.431540: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcuda.so.1'; dlerror: libcuda.so.1: cannot open shared object file: No such file or directory
2021-11-30 18:32:03.431847: W tensorflow/stream_executor/cuda/cuda_driver.cc:269] failed call to cuInit: UNKNOWN ERROR (303)
2021-11-30 18:32:03.432122: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:156] kernel driver does not appear to be running on this host (LAPTOP-GP5BU3LN): /proc/driver/nvidia/version does not exist
2021-11-30 18:32:03.437002: I tensorflow/core/platform/cpu_feature_guard.cc:151] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.

## Load music file and get prediction

In [3]:
filename = '/mnt/d/data-science/le-wagon/autotab/data/GuitarSet/audio/audio_mic/00_Rock2-142-D_solo_mic.wav'
x_new = load_x_new(filename)

In [4]:
y_pred = model.predict(x_new)

In [25]:
y_pred.shape

(1165, 6, 21)

## Get expanded tabs from make_full_tab

In [5]:
full_tab = make_full_tab(y_pred,len(y_pred))

/mnt/d/data-science/le-wagon/autotab/autotab/TabPrediction.py:51: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead.  To get a de-fragmented frame, use `newframe = frame.copy()`
  tablature[frame_idx] = fret

In [6]:
full_tab

,0,1,2,3,4,5,6,7,8,9,...,1155,1156,1157,1158,1159,1160,1161,1162,1163,1164
E,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,...,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1
A,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,...,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1
D,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,...,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1
G,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,...,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1
B,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,...,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1
e,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,...,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1

In [24]:
full_tab.loc[:,16:30]

   16  17  18  19  20  21  22  23  24  25  26  27  28  29  30
E  -1  -1  -1  -1  -1  -1  -1  -1  -1  -1  -1  -1  -1  -1  -1
A  -1  -1  -1  -1  -1  -1  -1  -1  -1  -1  -1  -1  -1  -1  -1
D  -1  -1  -1  -1  -1  -1  -1  -1  -1   5   5   5   5  -1  -1
G  -1  -1  -1  -1  -1  -1  -1  -1  -1  -1  -1  -1  -1  -1  -1
B  -1  -1  -1  -1  -1  -1  -1  -1  -1   8   8   8   8   8   8
e  -1  -1  -1  -1  -1  -1  -1  -1  -1  -1  -1  -1  -1  -1  -1

In [19]:
tp.print_tabs(full_tab)

e|----------------|----------------|----------------|----------------|----------------|
B|----------------|----------------|----------------|----------------|----------------|
G|----------------|----------------|----------------|----------------|----------------|
D|----------------|----------------|----------------|----------------|----------------|
A|----------------|----------------|----------------|----------------|----------------|
E|----------------|----------------|----------------|----------------|----------------|

e|----------------|----------------|----------------|----------------|----------------|
B|----------------|----------------|----------------|----------------|---5101010101055|
G|----------------|----------------|----------------|----------------|----------------|
D|----------------|----------------|----------------|----------------|----------------|
A|----------------|----------------|----------------|----------------|----------------|
E|----------------|----------------|----------------|----------------|----------------|

e|----------------|----------------|----------------|----------------|----------------|
B|5----------55---|----101010101010|10---8888888----|----------------|-101010101010--3|
G|------999-------|----------------|----------------|-------------777|7777777777777--5|
D|----------------|----------------|----------------|----------------|----------------|
A|----------------|----------------|----------------|----------------|----------------|
E|----------------|----------------|----------------|----------------|----------------|

e|----------------|----------------|----------------|----------------|----------------|
B|33333333333-----|------------555-|-------------555|555-------------|---------33-----|
G|5555555599999999|9999999999------|----55555-------|-------673------|---------5555555|
D|----------------|----------------|----------------|------7788------|----------------|
A|----------------|----------------|----------------|----------------|----------------|
E|----------------|----------------|----------------|----------------|----------------|

e|----------------|----------------|----------------|----------------|----------------|
B|-------------555|55--------------|----------------|----------------|----------------|
G|99--------------|--4444444444----|----------------|----------------|----------------|
D|----------------|--9999----------|---------7777777|7---------------|----------------|
A|----------------|----------------|----------------|----------------|----------------|
E|----------------|----------------|----------------|----------------|----------------|

e|----------------|----------------|----------------|----------------|----------------|
B|----------------|----------------|----------------|----------------|----------------|
G|----------------|----------------|----------------|----------------|----------------|
D|----------------|----------555555|555-------------|----------------|----------------|
A|----------------|----------------|----------------|----------------|----------------|
E|----------------|----------------|----------------|----------------|----------------|

e|----------------|----------------|----------------|----------------|----------------|
B|----------------|----------------|----------------|----------------|----------------|
G|----------------|----------------|----------------|----------------|----------------|
D|----------------|----------------|----------------|----------------|----------------|
A|----------------|----------------|----------------|----------------|----------------|
E|----------------|----------------|----------------|----------------|----------------|

e|----------------|----------------|----------------|----------------|----------------|
B|----------------|----------------|----------------|----------------|----------------|
G|----------------|----------------|----------------|----------------|----------------|
D|----------------|-------2222222-3|33--------555555|5------------333|33--------------|
A|----------------|-------3333-----|----------------|----------------|----------------|
E|----------------|----------------|----------------|----------------|----------------|

e|----------------|----------------|----------------|----------------|----------------|
B|----------------|----------------|----------------|----------------|----------------|
G|----------------|----------------|----------------|----------------|----------------|
D|----------------|--5-------------|----------------|-----77---------|----------------|
A|----------------|----------------|----------------|----------------|----------------|
E|----------------|----------------|----------------|----------------|----------------|

e|----------------|----------------|----------------|----------------|----------------|
B|----------------|----------------|----------------|----------------|----------------|
G|----------------|----------------|----------------|----------------|----------------|
D|----------------|----------------|----------------|----------------|------3---------|
A|----------------|----------------|----------------|----------------|----------------|
E|----------------|----------------|----------------|----------------|----------------|

e|----------------|----------------|----------------|----------------|----------------|
B|----------------|----------------|----------------|----------------|----------------|
G|----------------|----------------|----------------|----------------|----------------|
D|----------------|----------------|----------------|-----------88---|----------------|
A|----------------|----------------|----------------|----------------|----------------|
E|----------------|----------------|----------------|----------------|----------------|

e|----------------|----------------|----------------|----------------|----------------|
B|----------------|----------------|----------------|----------------|----------------|
G|----------------|----------------|----------------|----------------|----------------|
D|----------------|----------------|----------------|----------------|----------------|
A|----------------|----------------|----------------|----------------|----------------|
E|----------------|----------------|----------------|----------------|----------------|

e|----------------|----------------|----------------|----------------|----------------|
B|----------------|----------------|----------------|----------------|----------------|
G|----------------|----------------|----------------|----------------|----------------|
D|----------------|----------------|----------------|----------------|----------------|
A|----------------|----------------|----------------|----------------|----------------|
E|----------------|----------------|----------------|----------------|----------------|

e|----------------|----------------|----------------|----------------|----------------|
B|-888------------|----------------|----------------|----------------|----------------|
G|----------------|----------------|----------------|----------------|----------------|
D|----------------|----------------|----------------|----------------|----------------|
A|----------------|----------------|----------------|----------------|----------------|
E|----------------|----------------|----------------|----------------|----------------|

e|----------------|----------------|-------------
B|----------------|----------------|----------------|---------------
G|----------------|----------------|-------------
D|----------------|----------------|-------------
A|----------------|----------------|-------------
E|----------------|----------------|-------------

## Make an empty Tablature Dynamic_tab

In [7]:
dynamic_tab = tp.make_empty_tab()

## Make a counter to count columns written

In [8]:
col_write = 0

## Make a | column. Also for every 16 column, make a pipe column

## Make a counter for columns read

In [9]:
col_read=0

## Starting with 0 column, check UPTO next 4 columns, every time.increasing column read counter

In [10]:
full_tab[0]

E   -1
A   -1
D   -1
G   -1
B   -1
e   -1
Name: 0, dtype: int64

In [11]:
full_tab[9]

E   -1
A   -1
D   -1
G   -1
B   -1
e   -1
Name: 9, dtype: int64

In [12]:
full_tab[0].equals(full_tab[1])

True

In [13]:
full_tab.shape[1]

1165

In [21]:
col_read=0
col_write=0
n=5
total_frames = full_tab.shape[1]
while col_read < total_frames-1: #keep doing until you reach the last frame
    changed = False # set changed as false
    max_col = col_read+n # this is the window from current col + n cols ahead 5/0
    while ((not changed) and (col_read < max_col) and (col_read < total_frames-1)):  # only if not changed and full window not checked
        if not full_tab[col_read].equals(full_tab[col_read+1]):
            # if current column doesnt equal next column, meaning change
            dynamic_tab[col_write] = full_tab[col_read] # write this col to the dynamic tab
            col_write = col_write + 1 # advance the write counter
            changed = True # set changed to true
        col_read = col_read + 1 # advance the read counter, either ways
    if not changed: # this means the entire window was checked but no change
        dynamic_tab[col_write] = full_tab[col_read-1] # so write the last entry of this window
        col_write = col_write + 1  # advance the write counter
print(col_write)
print(col_read)
#need to take care of the last column
# if not dynamic_tab[col_write].equals(full_tab[col_read]):#if last written doesnt equal to last col in full_tab
#     dynamic_tab[col_write + 1] = full_tab[col_read] #write this column

263
1164

In [22]:
full_tab.loc[:, 0:15]

   0   1   2   3   4   5   6   7   8   9   10  11  12  13  14  15
E  -1  -1  -1  -1  -1  -1  -1  -1  -1  -1  -1  -1  -1  -1  -1  -1
A  -1  -1  -1  -1  -1  -1  -1  -1  -1  -1  -1  -1  -1  -1  -1  -1
D  -1  -1  -1  -1  -1  -1  -1  -1  -1  -1  -1  -1  -1  -1  -1  -1
G  -1  -1  -1  -1  -1  -1  -1  -1  -1  -1  -1  -1  -1  -1  -1  -1
B  -1  -1  -1  -1  -1  -1  -1  -1  -1  -1  -1  -1  -1  -1  -1  -1
e  -1  -1  -1  -1  -1  -1  -1  -1  -1  -1  -1  -1  -1  -1  -1  -1

In [23]:
dynamic_tab

,0,1,2,3,4,5,6,7,8,9,...,253,254,255,256,257,258,259,260,261,262
E,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,...,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1
A,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,...,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1
D,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,...,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1
G,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,...,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1
B,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,...,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1
e,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,...,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1

In [24]:
tp.print_tabs(dynamic_tab)

e|----------------|----------------|----------------|----------------|----------------|
B|----------------|--------------51|05--5---1010-88-|----1010-333----|-5----55------33|
G|----------------|----------------|---99-----------|----7777-5599999|----5----673---5|
D|----------------|----------------|----------------|----------------|--------7788----|
A|----------------|----------------|----------------|----------------|----------------|
E|----------------|----------------|----------------|----------------|----------------|

e|----------------|----------------|----------------|----------------|----------------|
B|-----5----------|----------------|----------------|----------------|----------------|
G|59----444-------|----------------|----------------|----------------|----------------|
D|------9-----77--|----------55----|----------------|----------22-3--|55---3-------5--|
A|----------------|----------------|----------------|----------3-----|----------------|
E|----------------|----------------|----------------|----------------|----------------|

e|----------------|----------------|----------------|----------------|----------------|
B|----------------|----------------|----------------|----------------|---------------8|
G|----------------|----------------|----------------|----------------|----------------|
D|-----7----------|---------3------|--------8-------|----------------|----------------|
A|----------------|----------------|----------------|----------------|----------------|
E|----------------|----------------|----------------|----------------|----------------|

e|----------------|-------
B|----------------|------------
G|----------------|-------
D|----------------|-------
A|----------------|-------
E|----------------|-------

## If there is a change, add current column to dynamic tab, and redo loop at current column read counter